### PR TITLE
feat: list MPD decoder plugins (modal/cli)

### PR DESCRIPTION
**Pull request by soifou**
For the modal I chose the keybind `P` (mnemonic for `P`lugins) but I don't know if it deserves a default binding as it is purely informational. Tell me what do you think.

CLI

```sh
$ rmpc decoders

[{"name":"mad","suffixes":["mp2","mp3"],"mime_types":["audio/mpeg"]},{"name":"mpg123","suffixes":["mp3"],"mime_types":[]},{"name":"vorbis","suffixes":["oga","ogg"],"mime_types":["application/ogg","application/x-ogg","audio/ogg","audio/vorbis","audio/vorbis+ogg","audio/x-ogg","audio/x-vorbis","audio/x-vorbis+ogg"]},{"name":"oggflac","suffixes":["oga","ogg"],"mime_types":["application/ogg","application/x-ogg","audio/ogg","audio/x-flac+ogg","audio/x-ogg"]},{"name":"flac","suffixes":["flac"],"mime_types":["application/flac","application/x-flac","audio/flac","audio/x-flac"]},{"name":"opus","suffixes":["oga","ogg","opus"],"mime_types":["application/ogg","audio/ogg","audio/opus"]},{"name":"sndfile","suffixes":["aif","aiff","au","caf","htk","iff","paf","pvf","sd2","sf","snd","svx","voc","w64","wav","xi"],"mime_types":["audio/aiff","audio/wav","audio/x-aiff","audio/x-wav"]},{"name":"dsdiff","suffixes":["dff"],"mime_types":["application/x-dff","audio/x-dff","audio/x-dsd"]},{"name":"dsf","suffixes":["dsf"],"mime_types":["application/x-dsf","audio/x-dsd","audio/x-dsf"]},{"name":"faad","suffixes":["aac"],"mime_types":["audio/aac","audio/aacp"]},{"name":"mpcdec","suffixes":["mpc"],"mime_types":[]},{"name":"wavpack","suffixes":["wv"],"mime_types":["audio/x-wavpack"]},{"name":"openmpt","suffixes":["669","amf","ams","c67","dbm","digi","dmf","dsm","dtm","far","gdm","ice","imf","it","j2b","m15","mdl","med","mmcmp","mms","mo3","mod","mptm","mt2","mtm","nst","okt","oxm","plm","ppm","psm","pt36","ptm","s3m","sfx","sfx2","st26","stk","stm","stp","ult","umx","wow","xm","xpk"],"mime_types":[]},{"name":"modplug","suffixes":["669","amf","ams","dbm","dfm","dsm","far","it","mdl","med","mod","mt2","mtm","okt","s3m","stm","ult","umx","xm"],"mime_types":[]},{"name":"mikmod","suffixes":["amf","dsm","far","gdm","imf","it","med","mod","mtm","s3m","stm","stx","ult","uni","xm"],"mime_types":[]},{"name":"sidplay","suffixes":["P00","mus","prg","sid","str"],"mime_types":[]},{"name":"fluidsynth","suffixes":["mid"],"mime_types":[]},{"name":"adplug","suffixes":["amd","d00","hsc","laa","rad","raw","sa2"],"mime_types":[]},{"name":"gme","suffixes":["ay","gbs","gym","hes","kss","nsf","nsfe","rsn","sap","spc","vgm","vgz"],"mime_types":[]},{"name":"ffmpeg","suffixes":["16sv","3g2","3gp","4xm","8svx","aa3","aac","ac3","adx","afc","aif","aifc","aiff","al","alaw","amr","anim","apc","ape","asf","atrac","au","aud","avi","avm2","avs","bap","bfi","c93","cak","cin","cmv","cpk","daud","dct","divx","dts","dv","dvd","dxa","eac3","film","flac","flc","fli","fll","flv","flx","g726","gsm","gxf","iss","m1v","m2t","m2ts","m2v","m4a","m4b","m4v","mad","mj2","mjpeg","mjpg","mka","mkv","mlp","mm","mmf","mov","mp+","mp1","mp2","mp3","mp4","mpc","mpeg","mpg","mpga","mpp","mpu","mve","mvi","mxf","nc","nsv","nut","nuv","oga","ogg","ogm","ogv","ogx","oma","omg","opus","psp","pva","qcp","qt","r3d","ra","ram","rl2","rm","rmvb","roq","rpl","rvc","shn","smk","snd","sol","son","spx","str","swf","tak","tgi","tgq","tgv","thp","ts","tsp","tta","uv","uv2","vb","vid","vmd","vob","voc","vp6","wav","webm","wma","wmv","wsaud","wsvga","wv","wve","xa","xvid"],"mime_types":["application/flv","application/m4a","application/mp4","application/octet-stream","application/ogg","application/x-ms-wmd","application/x-ms-wmz","application/x-ogg","application/x-shockwave-flash","application/x-shorten","audio/16sv","audio/8svx","audio/aac","audio/aacp","audio/ac3","audio/aiff","audio/amr","audio/basic","audio/flac","audio/m4a","audio/mp4","audio/mpeg","audio/musepack","audio/ogg","audio/opus","audio/qcelp","audio/vorbis","audio/vorbis+ogg","audio/wav","audio/x-16sv","audio/x-8svx","audio/x-aac","audio/x-ac3","audio/x-adx","audio/x-aiff","audio/x-alaw","audio/x-au","audio/x-dca","audio/x-eac3","audio/x-flac","audio/x-gsm","audio/x-mace","audio/x-matroska","audio/x-monkeys-audio","audio/x-mpd-ffmpeg","audio/x-mpeg","audio/x-ms-wax","audio/x-ms-wma","audio/x-musepack","audio/x-ogg","audio/x-pn-multirate-realaudio","audio/x-pn-realaudio","audio/x-speex","audio/x-tta","audio/x-voc","audio/x-vorbis","audio/x-vorbis+ogg","audio/x-wav","audio/x-wma","audio/x-wv","video/anim","video/msvideo","video/ogg","video/quicktime","video/theora","video/webm","video/x-dv","video/x-flv","video/x-matroska","video/x-mjpeg","video/x-mpeg","video/x-ms-asf","video/x-ms-wm","video/x-ms-wmv","video/x-ms-wmx","video/x-ms-wvx","video/x-msvideo","video/x-nut","video/x-pva","video/x-theora","video/x-vid","video/x-wmv","video/x-xvid"]},{"name":"pcm","suffixes":[],"mime_types":["audio/L16","audio/L24","audio/x-mpd-float","audio/x-mpd-cdda-pcm","audio/x-mpd-cdda-pcm-reverse","audio/x-mpd-alsa-pcm"]}]
```

Modal

image

### CODE REVIEW

**Comment by mierak** [comment]
Looks good to me. Could you also add a note in the [changelog](https://github.com/mierak/rmpc/blob/master/CHANGELOG.md) please? The default binding at on P is fine with me. Thanks!

**Comment by mierak** [comment]
There area two issues (click to select being off and there being empty space) with the long wrapped lines in the modal, though thats common for all the modals, I will fix those in a separate issue.

**Comment by soifou** [comment]
I updated the changelog, I'll fix the problem with the mouse click, I don't use the mouse so often that's why :)

**Comment by soifou** [comment]
Ok I misread, the empty spaces and click being off are both due to the wrapped lines so yeah it'll happen in every others modals using textwrap... Do you want those fixed before merging this?

**Comment by mierak** [comment]
Nah, Im fine with merging it like this, its my mistake anyway. I will fix it tomorrow or the day after.

**Comment by mierak** [comment]
Merged, thanks!

**Pull request merged**
